#!/bin/bash
set -e

# Path to the DB config file inside the container
DB_CONFIG="/var/www/html/tcexam/shared/config/tce_db_config.php"

echo "Configuring TCExam Database settings in $DB_CONFIG..."

# We overwrite the file with the specific constants needed for Docker
# We use the ENV variables passed from docker-compose
cat <<EOF > $DB_CONFIG
<?php
// Auto-generated by Docker Entrypoint
define('K_DATABASE_TYPE', 'MYSQL');
define('K_DATABASE_HOST', '${DB_HOST}');
define('K_DATABASE_PORT', '3306');
define('K_DATABASE_NAME', '${DB_NAME}');
define('K_DATABASE_USER_NAME', '${DB_USER}');
define('K_DATABASE_USER_PASSWORD', '${DB_PASSWORD}');
define('K_TABLE_PREFIX', 'tce_');

// Keep the table definitions standard (taken from your provided file)
define('K_TABLE_SESSIONS', K_TABLE_PREFIX.'sessions');
define('K_TABLE_USERS', K_TABLE_PREFIX.'users');
define('K_TABLE_MODULES', K_TABLE_PREFIX.'modules');
define('K_TABLE_SUBJECTS', K_TABLE_PREFIX.'subjects');
define('K_TABLE_QUESTIONS', K_TABLE_PREFIX.'questions');
define('K_TABLE_ANSWERS', K_TABLE_PREFIX.'answers');
define('K_TABLE_TESTS', K_TABLE_PREFIX.'tests');
define('K_TABLE_TEST_USER', K_TABLE_PREFIX.'tests_users');
define('K_TABLE_TESTUSER_STAT', K_TABLE_PREFIX.'testuser_stat');
define('K_TABLE_TEST_SUBJSET', K_TABLE_PREFIX.'test_subject_set');
define('K_TABLE_SUBJECT_SET', K_TABLE_PREFIX.'test_subjects');
define('K_TABLE_TESTS_LOGS', K_TABLE_PREFIX.'tests_logs');
define('K_TABLE_LOG_ANSWER', K_TABLE_PREFIX.'tests_logs_answers');
define('K_TABLE_GROUPS', K_TABLE_PREFIX.'user_groups');
define('K_TABLE_USERGROUP', K_TABLE_PREFIX.'usrgroups');
define('K_TABLE_TEST_GROUPS', K_TABLE_PREFIX.'testgroups');
define('K_TABLE_SSLCERTS', K_TABLE_PREFIX.'sslcerts');
define('K_TABLE_TEST_SSLCERTS', K_TABLE_PREFIX.'testsslcerts');
EOF

# Ensure permissions are correct
chown www-data:www-data $DB_CONFIG

echo "Database configuration updated."

# Start Apache
exec "$@"